global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  # minio
  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets:
        - 'localhost:9000'

  # prometheus
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
        - localhost:9090

  # cadvisor
  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
      - targets:
        - cadvisor:8080

